version: '3'
services: 
  master:
    image: assistente:master
    ports:
      - "3000:80" 
    build: .
  docs:
    image: assistente:docs
    ports:
      - "3001:80" 
    build: 
      context: .
      dockerfile: ./Dockerfile.docs