version: '3'
services:
  build:
    image: assistente:build
    build:
      context: .
  test:
    image: assistente:test
    build: .
  master:
    image: assistente:master
    ports:
      - "3000:3000" 
    build: .
